name: CI/CD MLflow Stroke Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "data_preprocessing.csv"
  TARGET_VAR: "stroke"
  MODEL_NAME: "stroke-model"

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn imbalanced-learn

      - name: Download Dataset
        run: |
          wget "${{ env.CSV_URL }}" -O MLProject/data_preprocessing.csv

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | cut -d'/' -f4)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Image from MLflow Model
        run: |
          mlflow models build-docker \
            --model-uri "MLProject/mlruns/0/$RUN_ID/artifacts/model" \
            --name ${{ env.MODEL_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.TOKEN_STROKE }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.MODEL_NAME }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.MODEL_NAME }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.MODEL_NAME }}:latest
